server:
  port: 8192
  context-path: /

# 服务节点,要求分布式下每个节点不同
node: 01

spring:
  dubbo:
    application:
      name: xxpay-agent
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: org.xxpay.agent
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      number_format: 0.##

  jackson:
    serialization:
      INDENT_OUTPUT: true
  profiles:
     active: prod

# JWT
jwt:
  cookie: XxPay_Agent_Token
  secret: XxpPayGood
  expiration: 604800 # 7天

logging:
  file: ./log/xxpay-agent.log

config:
  payUrl: http://pay.changlepay.com/api

